" Generated by matugen - do not edit manually
set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

let s:bg      = "{{colors.background.default.hex}}"
let s:fg      = "{{colors.on_background.default.hex}}"
let s:surf    = "{{colors.surface.default.hex}}"
let s:surfv   = "{{colors.surface_variant.default.hex}}"
let s:primary = "{{colors.primary.default.hex}}"
let s:on_pri  = "{{colors.on_primary.default.hex}}"
let s:second  = "{{colors.secondary.default.hex}}"
let s:tertiary= "{{colors.tertiary.default.hex}}"
let s:outline = "{{colors.outline.default.hex}}"
let s:error   = "{{colors.error.default.hex}}"

exe "hi Normal       guibg=" . s:bg      . " guifg=" . s:fg
exe "hi NormalFloat  guibg=" . s:surf    . " guifg=" . s:fg
exe "hi Comment      guifg=" . s:outline . " gui=italic"
exe "hi Keyword      guifg=" . s:primary . " gui=bold"
exe "hi Function     guifg=" . s:tertiary
exe "hi String       guifg=" . s:second
exe "hi Number       guifg=" . s:tertiary
exe "hi Type         guifg=" . s:primary
exe "hi Constant     guifg=" . s:tertiary
exe "hi Identifier   guifg=" . s:fg
exe "hi Statement    guifg=" . s:primary . " gui=bold"
exe "hi Special      guifg=" . s:second
exe "hi StatusLine   guibg=" . s:surfv   . " guifg=" . s:fg
exe "hi LineNr       guifg=" . s:outline
exe "hi CursorLineNr guifg=" . s:primary . " gui=bold"
exe "hi Visual       guibg=" . s:surfv
exe "hi Search       guibg=" . s:primary . " guifg=" . s:on_pri
exe "hi MatchParen   guibg=" . s:primary . " guifg=" . s:on_pri
exe "hi DiagnosticError guifg=" . s:error
