" Generated by matugen - do not edit manually
set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

let s:bg      = "#111318"
let s:fg      = "#e2e2e9"
let s:surf    = "#111318"
let s:surfv   = "#44474e"
let s:primary = "#a9c7ff"
let s:on_pri  = "#09305f"
let s:second  = "#bdc7dc"
let s:tertiary= "#dcbce1"
let s:outline = "#8e9099"
let s:error   = "#ffb4ab"

exe "hi Normal       guibg=" . s:bg      . " guifg=" . s:fg
exe "hi NormalFloat  guibg=" . s:surf    . " guifg=" . s:fg
exe "hi Comment      guifg=" . s:outline . " gui=italic"
exe "hi Keyword      guifg=" . s:primary . " gui=bold"
exe "hi Function     guifg=" . s:tertiary
exe "hi String       guifg=" . s:second
exe "hi Number       guifg=" . s:tertiary
exe "hi Type         guifg=" . s:primary
exe "hi Constant     guifg=" . s:tertiary
exe "hi Identifier   guifg=" . s:fg
exe "hi Statement    guifg=" . s:primary . " gui=bold"
exe "hi Special      guifg=" . s:second
exe "hi StatusLine   guibg=" . s:surfv   . " guifg=" . s:fg
exe "hi LineNr       guifg=" . s:outline
exe "hi CursorLineNr guifg=" . s:primary . " gui=bold"
exe "hi Visual       guibg=" . s:surfv
exe "hi Search       guibg=" . s:primary . " guifg=" . s:on_pri
exe "hi MatchParen   guibg=" . s:primary . " guifg=" . s:on_pri
exe "hi DiagnosticError guifg=" . s:error
